name: Build and Release Desktop App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Cấp quyền cho workflow để có thể ghi (tạo release) vào repository
permissions:
  contents: write

jobs:
  # === JOB 1: BUILD CHO WINDOWS ===
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows EXE
        run: pyinstaller --onefile --windowed --name="AnhBiaTool-Windows" main.py
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: dist/AnhBiaTool-Windows.exe

  # === JOB 2: BUILD CHO LINUX ===
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install System Dependencies for PyQt6
        # Cài đặt các thư viện Qt6 cần thiết cho Linux
        run: sudo apt-get update && sudo apt-get install -y libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-shape0 libxkbcommon-x11-0

      - name: Install Python Dependencies
        run: pip install -r requirements.txt && pip install pyinstaller

      - name: Build Linux Executable
        run: pyinstaller --onefile --name="AnhBiaTool-Linux" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/AnhBiaTool-Linux

  # === JOB 3: BUILD CHO MACOS ===
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt && pip install pyinstaller

      - name: Build macOS App
        # Sử dụng chế độ onedir (không có --onefile) để đảm bảo ổn định trên macOS
        run: pyinstaller --windowed --name="AnhBiaTool-macOS" main.py
      
      - name: Zip the .app bundle
        # Thư mục .app được tạo ra trong thư mục dist
        run: zip -r dist/AnhBiaTool-macOS.zip dist/AnhBiaTool-macOS.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/AnhBiaTool-macOS.zip # Tải lên file .zip

  # === JOB 4: TẠO RELEASE (CHẠY SAU KHI CẢ 3 BẢN BUILD THÀNH CÔNG) ===
  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos] # Phụ thuộc vào cả 3 job build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        # Tải tất cả các artifacts vào thư mục làm việc, mỗi artifact một thư mục con

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          # Tạo một tag duy nhất cho mỗi lần chạy dựa trên số thứ tự build
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }} (Win, Linux, macOS)
          body: |
            Build tự động từ commit: `${{ github.sha }}`
            Đây là phiên bản đang trong quá trình phát triển. Tải về file phù hợp với hệ điều hành của bạn.
          # Đánh dấu đây là phiên bản chưa chính thức (pre-release)
          prerelease: true
          # Đường dẫn đến các file cần tải lên, dựa trên tên artifact đã tạo
          files: |
            windows-app/AnhBiaTool-Windows.exe
            linux-app/AnhBiaTool-Linux
            macos-app/AnhBiaTool-macOS.zip
